language: python

python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls
  - cd estdel
  - python setup.py install

script:
  - coverage run --source estdel setup.py test

after_success:
    coveralls