language: python

python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls
  - python setup.py install

script:
  - coverage run --omit=estdel/__branch__.py,estdel/__gitlog__.py,estdel/__version__.py --source estdel setup.py test

after_success:
    coveralls